linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - golint
    - gofmt
    - goimports
    - unconvert
    - unparam
    - gocritic
    - gochecknoglobals
    - nakedret
    - misspell
    - nolintlint
    - asciicheck
    - revive
